spring:
  h2:
    console:
      enabled: true
      path: /h2-console-vot

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/vot1
    username: sa
    password:


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true